{
 "title": "慢SQL",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "db_name",
    "label": "数据库名称",
    "query": "select distinct db_name from polardb_slow_log WHERE $__unixEpochFilter(data_timestamp)"
   },
   {
    "name": "sql_template_id",
    "label": "SQL模板ID",
    "query": "select distinct sql_template_id from polardb_slow_log WHERE $__unixEpochFilter(data_timestamp)"
   }
  ]
 },
 "panels": [
  {
   "title": "慢SQL-模板",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n\tt.data_timestamp AS \"time\",\n\tcount( 1 ) AS \"每小时出现次数\" \nFROM\n\t(\n\tSELECT DISTINCT sql_template_id,\n\t\tdata_timestamp \n\tFROM\n\t\tpolardb_slow_log \n\tWHERE\n\t\t$__unixEpochFilter(data_timestamp)\n\tAND db_name IN ( $db_name )\n\tand sql_template_id in ($sql_template_id)\n\t) t \nGROUP BY\n\tt.data_timestamp \nORDER BY\n\tt.data_timestamp"
    }
   ]
  },
  {
   "title": "慢SQL",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \r\n  t.data_timestamp AS \"time\",\r\n  count(1) as \"每小时出现次数\"\r\nfrom (\r\nselect data_timestamp\r\nfrom polardb_slow_log\r\nWHERE\r\n  $__unixEpochFilter(data_timestamp)\r\n  and db_name in ($db_name)\r\n\t)t\r\ngroup by data_timestamp\r\nORDER BY data_timestamp"
    }
   ]
  },
  {
   "title": "慢SQL模板详情",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  t.id AS 'SQL模板ID',\n\tt.db_name AS '数据库',\n\tt.times AS '次数',\n\tFLOOR( t.avg_qt ) AS '平均耗时(秒)',\n\tt.max_qt AS '最大耗时(秒)',\n\tt.min_qt AS '最小耗时(秒)',\n\tt.parse_row_counts AS '扫描行数',\n\tt.sql_text AS 'SQL模板' \nFROM\n\t(\n\tSELECT\n\t\tpslt.id,\n\t\tpslt.db_name,\n\t\tCONVERT ( pslt.sql_text USING utf8 ) sql_text,\n\t\tpsl.data_timestamp,\n\t\tpsl.parse_row_counts,\n\t\tpsl.execution_start_time,\n\t\tcount( 1 ) AS times,\n\t\tavg( psl.query_times ) avg_qt,\n\t\tmax( psl.query_times ) max_qt,\n\t\tmin( psl.query_times ) min_qt \n\tFROM\n\t\tpolardb_slow_log_template pslt\n\t\tLEFT JOIN polardb_slow_log psl ON pslt.db_name = psl.db_name \n\t\tAND pslt.id = psl.sql_template_id\n\tWHERE $__unixEpochFilter(data_timestamp) and pslt.db_name in ($db_name) and pslt.id in ($sql_template_id)\n\tGROUP BY\n\t\tdb_name,\n\t\tsql_text \n\t) t \nORDER BY\n\tt.times DESC"
    }
   ]
  },
  {
   "title": "慢SQL详细清单",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  execution_start_time as \"执行开始时间\",\n  query_times as \"耗时(秒)\",\n  db_name as \"数据库\",\n  parse_row_counts as '扫描行数',\n  convert(sql_text using utf8) \"sql\"\nFROM polardb_slow_log\nWHERE\n  $__unixEpochFilter(data_timestamp)\n    and db_name in ($db_name)\n    and sql_template_id in ($sql_template_id)\nORDER BY data_timestamp"
    }
   ]
  }
 ]
}