{
 "title": "慢SQL",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "db_name",
    "label": "数据库名称",
    "query": "select distinct db_name from polardb_slow_log"
   }
  ]
 },
 "panels": [
  {
   "title": "慢SQL-模板",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \r\n  t.data_timestamp AS \"time\",\r\n  count(1) as \"每小时出现次数\"\r\nfrom (\r\nselect distinct convert(sql_template using utf8) sql_text, data_timestamp\r\nfrom polardb_slow_log\r\nWHERE\r\n  $__unixEpochFilter(data_timestamp)\r\n  and db_name in ($db_name)\r\n\t)t\r\ngroup by data_timestamp\r\nORDER BY data_timestamp"
    }
   ]
  },
  {
   "title": "慢SQL",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \r\n  t.data_timestamp AS \"time\",\r\n  count(1) as \"每小时出现次数\"\r\nfrom (\r\nselect data_timestamp\r\nfrom polardb_slow_log\r\nWHERE\r\n  $__unixEpochFilter(data_timestamp)\r\n  and db_name in ($db_name)\r\n\t)t\r\ngroup by data_timestamp\r\nORDER BY data_timestamp"
    }
   ]
  },
  {
   "title": "慢SQL模板详情",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tt.execution_start_time as '执行开始时间', t.db_name as '数据库', t.times as '次数',\r\n\tt.avg_qt as '平均耗时(秒)', t.max_qt as '最大耗时(秒)', t.avg_qt as '最小耗时(秒)',\r\n\tt.sql_template as 'SQL模板'\r\nfrom (\r\n\tselect distinct convert(sql_template using utf8) sql_template, data_timestamp, db_name,\r\n\t\texecution_start_time, count(1) as times,\r\n\t\tavg(query_times) avg_qt, max(query_times) max_qt, min(query_times) min_qt\r\n\tfrom polardb_slow_log\r\n\tWHERE\r\n\t\t$__unixEpochFilter(data_timestamp)\r\n\t\tand db_name in ($db_name)\r\n\tgroup by sql_template\r\n\t)t"
    }
   ]
  },
  {
   "title": "慢SQL详细清单",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  execution_start_time as \"执行开始时间\",\n  query_times as \"耗时(秒)\",\n  db_name as \"数据库\",\n  convert(sql_text using utf8) \"sql\"\nFROM polardb_slow_log\nWHERE\n  $__unixEpochFilter(data_timestamp)\n    and db_name in ($db_name)\nORDER BY data_timestamp"
    }
   ]
  }
 ]
}